---

ESXi_HOSTS:
  - ESXi_HOST: "ESXi-01"
    NAME: "ESXi01"
    IP_ADDRESS: "192.168.255.221"
    MAC_ADDRESS: "00-0c-29-64-e4-1e"
  - ESXi_HOST: "ESXi-02"
    NAME: "ESXi02"
    IP_ADDRESS: "192.168.255.222"
    MAC_ADDRESS: "00-0c-29-66-92-f3"

USER: "ansible"
GROUP: "ansible"

OSDIRNAME: "ESXi-7.0"

SYSLINUX_URL: "https://mirrors.edge.kernel.org/pub/linux/utils/boot/syslinux/3.xx/syslinux-3.86.zip"

dhcp_docker_image_name: "dhcp-server"
dhcp_docker_container_name: "dhcp-server"
dhcp_docker_container_ip: "192.168.255.15"

http_docker_image_name: "web-server"
http_docker_container_name: "web-server"
http_docker_container_ip: "192.168.255.17"

tftp_docker_image_name: "tftp-server"
tftp_docker_container_name: "tftp-server"
tftp_docker_container_ip: "192.168.255.16"

SUBNET: "192.168.255.0"
NETMASK: "255.255.255.0"
NETWORK: "192.168.255.0/24"
GATEWAY: "192.168.255.2"
BRODCAST: "192.168.255.255"
START_IP_RANGE: "192.168.255.31"
END_IP_RANGE: "192.168.255.240"
DOMAIN_NAME: "vgit.local"
DNSSERVER_IP: "8.8.8.8"

NEXTSERVER_IP: "192.168.255.16"

WEBSERVER_IP: "192.168.255.17"
