---

   - name: UEFI - Create Host specific boot configurations
     block:
       - name: Create directory MAC-Address specific
         file:
           path: "./{{role_name}}/files/tftpboot/{{ OSDIRNAME }}/efi/boot/01-{{ item.MAC_ADDRESS }}"
           mode: 0775
           state: directory
         with_items:
           "{{ ESXi_HOSTS }}"

       - name: Copy boot.cfg to MAC-Address specific directory
         ansible.builtin.copy:
           src: "./{{role_name}}/files/tftpboot/{{ OSDIRNAME }}/efi/boot/boot.cfg"
           dest: "./{{role_name}}/files/tftpboot/{{ OSDIRNAME }}/efi/boot/01-{{ item.MAC_ADDRESS }}/"
         with_items:
           "{{ ESXi_HOSTS }}"

       - name: Edit line "kernelopt=" in MAC-Address specific boot.cfg file
         ansible.builtin.lineinfile:
           path: "./{{role_name}}/files/tftpboot/{{ OSDIRNAME }}/efi/boot/01-{{ item.MAC_ADDRESS }}/boot.cfg"
           regexp: '^kernelopt='
           line: kernelopt=ks=http://{{ WEBSERVER_IP }}/{{ item.MAC_ADDRESS }}.cfg
         with_items:
           "{{ ESXi_HOSTS }}"
