---

   - name: Install Docker module for Python
     pip:
      name: docker

   - name: Install Docker collection for Ansible
     command: ansible-galaxy collection install community.docker

   - name: Create macvlan network
     community.docker.docker_network:
       name: "MACVLAN"
       driver: "macvlan"
       driver_options:
         parent: "{{ ansible_default_ipv4.interface }}"
       ipam_config:
        - subnet: '{{ NETWORK }}'
          gateway: '{{ GATEWAY }}'
